spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/travel
    platform: postgres
    username: postgres
    password: 1234
  profiles:
    include: oauth

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.transaction.jta.platform: org.hibernate.service.jta.JtaPlatform
      hibernate:
        format_sql: true

    redis:
      host: localhost
      port: 6380

jwt:
  key: c3ByaW5nLWJvb3QtYXBpLWp3dC1zZWNyZXQta2V5LXN1cGVyLXNlY3JldC15ZXMteWVzLXllcy0yNAo=